### ISSUE TITLE
TESTS?

### ISSUE THREAD

**Issue by dubhcait** [FAC-Sixteen/jokoanna#13]
OMG ye got tests going. Well done!!

**Comment by RohanSSS** [comment]
even though the tests pass they give this big message.

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: HTMLFormElement.prototype.submit
        at module.exports (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLFormElementImpl.submit (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:77:5)
        at HTMLFormElementImpl._doSubmit (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:72:12)
        at HTMLInputElementImpl._activationBehavior (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:222:14)
        at callEventBehaviorHook (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:130:19)
        at HTMLInputElementImpl.dispatchEvent (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:9)
        at HTMLInputElement.dispatchEvent (/home/rss/Documents/Coding/jokoanna/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at fireEvent (/home/rss/Documents/Coding/jokoanna/node_modules/dom-testing-library/dist/events.js:534:18)
        at Function.fireEvent.(anonymous function) [as click] (/home/rss/Documents/Coding/jokoanna/node_modules/dom-testing-library/dist/events.js:578:36)
        at /home/rss/Documents/Coding/jokoanna/node_modules/react-testing-library/dist/index.js:145:54 undefined
```

not sure what its for since it's pointing towards a file in node_modules. But if it can be fixed then it would be a good idea to do so, even if the tests are still passing with it appearing.
